# Introducción a los Tensores

Los **tensores** son una generalización de los escalares (0D), vectores (1D) y matrices (2D) a dimensiones superiores. En el contexto de las matemáticas y la ciencia de datos, los tensores son estructuras de datos multidimensionales que pueden representar datos complejos y relaciones entre ellos.

## ¿Qué es un Tensor?

Matemáticamente, un tensor es un objeto que es invariantemente definido bajo transformaciones lineales. Sin embargo, en el contexto de programación y ciencia de datos, un tensor es simplemente una matriz multidimensional.

- **Escalar**: Un solo número (tensor de orden 0).
- **Vector**: Una lista de números (tensor de orden 1).
- **Matriz**: Una cuadrícula de números (tensor de orden 2).
- **Tensor de orden N**: Una estructura de datos N-dimensional.

Por ejemplo, una imagen en color puede ser representada como un tensor de orden 3 con dimensiones (altura, anchura, canales de color).

## Notación Matemática

Un tensor de orden $ n $ en un espacio $ \mathbb{R}^{I_1 \times I_2 \times \dots \times I_n} $ puede ser representado como:

$$
\mathcal{T} \in \mathbb{R}^{I_1 \times I_2 \times \dots \times I_n}
$$

Donde $ I_k $ es la dimensión en el eje $ k $.



## Operaciones Matemáticas con Tensores

Antes de pasar a la creación de tensores en NumPy, introducimos algunas de las operaciones matemáticas más comunes con tensores:

### Producto Escalar para Vectores

El **producto escalar** (o producto punto) de dos vectores $ \mathbf{a}, \mathbf{b} \in \mathbb{R}^n $ se define como:

$$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i
$$

Donde $ a_i $ y $ b_i $ son los elementos de los vectores $ \mathbf{a} $ y $ \mathbf{b} $, respectivamente.

**Ejemplo:**

Sea $\mathbf{a} = [1, 2, 3, 4]$ y $\mathbf{b} = [5, 6, 7, 8]$, entonces el producto escalar es:

$$
\begin{align*}
\mathbf{a} \cdot \mathbf{b} &= a_1 b_1 + a_2 b_2 + a_3 b_3 + a_4 b_4 \\
&= (1)(5) + (2)(6) + (3)(7) + (4)(8) \\
&= 5 + 12 + 21 + 32 \\
&= 70
\end{align*}
$$

Por lo tanto, $\mathbf{a} \cdot \mathbf{b} = 70$.


In [1]:
### Ejemplo con python usando numpy
import numpy as np

# Definir los vectores
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Calcular el producto escalar
producto_escalar = np.dot(a, b)

print("El producto escalar de a y b es:", producto_escalar)

El producto escalar de a y b es: 70


### Multiplicación de Matrices

La **multiplicación de matrices** entre dos matrices $ A \in \mathbb{R}^{m \times n} $ y $ B \in \mathbb{R}^{n \times p} $ se define como:

$$
(AB)_{ij} = \sum_{k=1}^n A_{ik} B_{kj}
$$

Donde el elemento resultante $ (AB)_{ij} $ es la suma de los productos de los elementos de la fila $ i $ de la matriz $ A $ y la columna $ j $ de la matriz $ B $.

**Ejemplo:**

Sea $A$ una matriz de dimensión $2 \times 3$ y $B$ una matriz de dimensión $3 \times 2$:

$$
A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
\end{pmatrix}, \quad
B = \begin{pmatrix}
7 & 8 \\
9 & 10 \\
11 & 12 \\
\end{pmatrix}
$$

El producto $AB$ es una matriz de dimensión $2 \times 2$, donde:

$$
(AB)_{ij} = \sum_{k=1}^3 A_{ik} B_{kj}
$$

Calculamos cada elemento:

1. $(AB)_{11}$:

$$
\begin{align*}
(AB)_{11} &= A_{11} B_{11} + A_{12} B_{21} + A_{13} B_{31} \\
&= (1)(7) + (2)(9) + (3)(11) \\
&= 7 + 18 + 33 = 58
\end{align*}
$$

2. $(AB)_{12}$:

$$
\begin{align*}
(AB)_{12} &= A_{11} B_{12} + A_{12} B_{22} + A_{13} B_{32} \\
&= (1)(8) + (2)(10) + (3)(12) \\
&= 8 + 20 + 36 = 64
\end{align*}
$$

3. $(AB)_{21}$:

$$
\begin{align*}
(AB)_{21} &= A_{21} B_{11} + A_{22} B_{21} + A_{23} B_{31} \\
&= (4)(7) + (5)(9) + (6)(11) \\
&= 28 + 45 + 66 = 139
\end{align*}
$$

4. $(AB)_{22}$:

$$
\begin{align*}
(AB)_{22} &= A_{21} B_{12} + A_{22} B_{22} + A_{23} B_{32} \\
&= (4)(8) + (5)(10) + (6)(12) \\
&= 32 + 50 + 72 = 154
\end{align*}
$$

Entonces, el resultado de la multiplicación es:

$$
AB = \begin{pmatrix}
58 & 64 \\
139 & 154 \\
\end{pmatrix}
$$


In [2]:
# Definir las matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Multiplicar las matrices
AB = np.dot(A, B)

print("El resultado de la multiplicación AB es:")
print(AB)

El resultado de la multiplicación AB es:
[[ 58  64]
 [139 154]]



### Multiplicación de Tensores de Mayor Dimensión

Para tensores de mayor dimensión, la multiplicación se puede generalizar mediante el uso de la **contracción de índices**, donde se realiza la suma sobre ciertos ejes comunes entre los tensores involucrados.

**Ejemplo:**

Consideremos dos tensores de orden 3, $\mathcal{A} \in \mathbb{R}^{I \times J \times K}$ y $\mathcal{B} \in \mathbb{R}^{K \times L \times M}$. Podemos definir una operación de multiplicación sobre el índice $K$:

$$
\mathcal{C}_{i j l m} = \sum_{k=1}^K \mathcal{A}_{i j k} \mathcal{B}_{k l m}
$$

Esta operación resulta en un tensor $\mathcal{C} \in \mathbb{R}^{I \times J \times L \times M}$.


In [3]:
import numpy as np

# Definir los tensores
A = np.random.randint(1, 5, size=(2, 2, 3))
B = np.random.randint(1, 5, size=(3, 2, 2))

# Realizar la multiplicación sobre el índice compartido
C = np.tensordot(A, B, axes=([2], [0]))

print("Forma del tensor resultante C:", C.shape)
print("Tensor resultante C:")
print(C)


Forma del tensor resultante C: (2, 2, 2, 2)
Tensor resultante C:
[[[[22 15]
   [36 28]]

  [[11  8]
   [20 15]]]


 [[[ 9 14]
   [20 13]]

  [[20 21]
   [36 26]]]]



### Suma Elemento a Elemento

La **suma elemento a elemento** (también llamada suma Hadamard) de dos tensores $ \mathcal{A}, \mathcal{B} $ de la misma forma se define como:

$$
(\mathcal{A} + \mathcal{B})_{i_1, i_2, \dots, i_n} = \mathcal{A}_{i_1, i_2, \dots, i_n} + \mathcal{B}_{i_1, i_2, \dots, i_n}
$$

Cada elemento del tensor resultante es la suma de los elementos correspondientes de $ \mathcal{A} $ y $ \mathcal{B} $.

**Ejemplo:**

Sea $\mathcal{A}$ y $\mathcal{B}$ matrices de dimensión $2 \times 2$:

$$
\mathcal{A} = \begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}, \quad
\mathcal{B} = \begin{pmatrix}
5 & 6 \\
7 & 8 \\
\end{pmatrix}
$$

La suma elemento a elemento es:

$$
\mathcal{A} + \mathcal{B} = \begin{pmatrix}
1+5 & 2+6 \\
3+7 & 4+8 \\
\end{pmatrix} = \begin{pmatrix}
6 & 8 \\
10 & 12 \\
\end{pmatrix}
$$


In [4]:
import numpy as np

# Definir las matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Sumar elemento a elemento
suma = A + B

print("La suma elemento a elemento de A y B es:")
print(suma)

La suma elemento a elemento de A y B es:
[[ 6  8]
 [10 12]]



### Multiplicación Elemento a Elemento

La **multiplicación elemento a elemento** (también llamada producto Hadamard) de dos tensores $ \mathcal{A}, \mathcal{B} $ de la misma forma se define como:

$$
(\mathcal{A} \circ \mathcal{B})_{i_1, i_2, \dots, i_n} = \mathcal{A}_{i_1, i_2, \dots, i_n} \cdot \mathcal{B}_{i_1, i_2, \dots, i_n}
$$

Cada elemento del tensor resultante es el producto de los elementos correspondientes de $ \mathcal{A} $ y $ \mathcal{B} $.

**Ejemplo:**

Utilizando las mismas matrices $\mathcal{A}$ y $\mathcal{B}$ del ejemplo anterior:

$$
\mathcal{A} \circ \mathcal{B} = \begin{pmatrix}
1 \times 5 & 2 \times 6 \\
3 \times 7 & 4 \times 8 \\
\end{pmatrix} = \begin{pmatrix}
5 & 12 \\
21 & 32 \\
\end{pmatrix}
$$

In [5]:
import numpy as np

# Definir las matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Multiplicar elemento a elemento
producto_hadamard = A * B

print("El producto elemento a elemento de A y B es:")
print(producto_hadamard)


El producto elemento a elemento de A y B es:
[[ 5 12]
 [21 32]]


# Uso de frameworks para trabajar con tensores: tensorflow y pytorch

En el mundo del aprendizaje automático y el procesamiento de datos a gran escala, TensorFlow y PyTorch son dos de los frameworks más populares y ampliamente utilizados. Ambos están diseñados para trabajar con tensores y facilitan la implementación de modelos de aprendizaje profundo.

### ¿Qué son TensorFlow y PyTorch?

- TensorFlow: Desarrollado por Google Brain, TensorFlow es una biblioteca de código abierto para computación numérica y aprendizaje automático. Permite a los desarrolladores crear gráficos de flujo de datos, donde los nodos representan operaciones matemáticas y las aristas representan los datos multidimensionales (tensores) que fluyen entre ellos.

- PyTorch: Desarrollado por Facebook's AI Research lab (FAIR), PyTorch es otra biblioteca de código abierto que proporciona herramientas para construir y entrenar redes neuronales. A diferencia de TensorFlow, que originalmente utilizaba gráficos estáticos, PyTorch se basa en gráficos dinámicos, lo que facilita la construcción y modificación de modelos en tiempo real.

### ¿Por qué son necesarios?

Estos frameworks simplifican muchas de las tareas complejas involucradas en el desarrollo de modelos de aprendizaje profundo:

- Abstracción: Proporcionan una capa de abstracción sobre las operaciones matemáticas complejas, permitiendo a los desarrolladores centrarse en el diseño del modelo en lugar de en los detalles de implementación.

- Eficiencia: Optimizan automáticamente las operaciones matemáticas para aprovechar al máximo el hardware disponible, como CPUs y GPUs.

- Comunidad y Soporte: Ambos tienen una gran comunidad de desarrolladores y una amplia gama de recursos, tutoriales y ejemplos.

### Importancia de la Ejecución en GPU

Las GPUs (Unidades de Procesamiento Gráfico) están diseñadas para realizar cálculos en paralelo a alta velocidad, lo que es ideal para las operaciones matriciales y tensoriales intensivas en cómputo que se encuentran en el aprendizaje profundo.

- Aceleración: Ejecutar modelos en GPUs puede acelerar significativamente el entrenamiento y la inferencia.

- Escalabilidad: Permite manejar grandes volúmenes de datos y modelos más complejos.

- Optimización: Tanto TensorFlow como PyTorch proporcionan soporte integrado para ejecutar operaciones en GPUs, optimizando el rendimiento sin necesidad de ajustes manuales.

## Ejemplos de operaciones tensoriales con Tensorflow

In [6]:
import tensorflow as tf

# Producto escalar

# Definir los vectores
a = tf.constant([1, 2, 3, 4], dtype=tf.float32)
b = tf.constant([5, 6, 7, 8], dtype=tf.float32)

# Calcular el producto escalar
producto_escalar = tf.tensordot(a, b, axes=1)

print("El producto escalar de a y b es:", producto_escalar.numpy())

El producto escalar de a y b es: 70.0


In [7]:
# Multiplicación de matrices

# Definir las matrices
A = tf.constant([[1, 2, 3],
                 [4, 5, 6]], dtype=tf.float32)

B = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]], dtype=tf.float32)

# Multiplicar las matrices
AB = tf.matmul(A, B)

print("El resultado de la multiplicación AB es:")
print(AB.numpy())

El resultado de la multiplicación AB es:
[[ 58.  64.]
 [139. 154.]]


In [8]:
# Multiplicación de tensores de más dimensión

# Definir los tensores
A = tf.random.uniform(shape=(2, 2, 3), minval=1, maxval=5, dtype=tf.int32)
B = tf.random.uniform(shape=(3, 2, 2), minval=1, maxval=5, dtype=tf.int32)

# Realizar la multiplicación sobre el índice compartido
C = tf.tensordot(A, B, axes=([2], [0]))

print("Forma del tensor resultante C:", C.shape)

Forma del tensor resultante C: (2, 2, 2, 2)


In [9]:
# Suma elemento a elemento

# Definir las matrices
A = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)

B = tf.constant([[5, 6],
                 [7, 8]], dtype=tf.float32)

# Sumar elemento a elemento
suma = tf.add(A, B)

print("La suma elemento a elemento de A y B es:")
print(suma.numpy())

# Multiplicación elemento a elemento
# Definir las matrices
A = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.float32)

B = tf.constant([[5, 6],
                 [7, 8]], dtype=tf.float32)

# Multiplicar elemento a elemento
producto_hadamard = tf.multiply(A, B)

print("El producto elemento a elemento de A y B es:")
print(producto_hadamard.numpy())

La suma elemento a elemento de A y B es:
[[ 6.  8.]
 [10. 12.]]
El producto elemento a elemento de A y B es:
[[ 5. 12.]
 [21. 32.]]


## Ejemplos de operaciones tensoriales con pyTorch

In [10]:
import torch

# Producto escalar

# Definir los vectores
a = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
b = torch.tensor([5, 6, 7, 8], dtype=torch.float32)

# Calcular el producto escalar
producto_escalar = torch.dot(a, b)

print("El producto escalar de a y b es:", producto_escalar.item())


El producto escalar de a y b es: 70.0


In [11]:
# Multiplicación de matrices

# Definir las matrices
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.float32)

B = torch.tensor([[7, 8],
                  [9, 10],
                  [11, 12]], dtype=torch.float32)

# Multiplicar las matrices
AB = torch.matmul(A, B)

print("El resultado de la multiplicación AB es:")
print(AB)


El resultado de la multiplicación AB es:
tensor([[ 58.,  64.],
        [139., 154.]])


In [12]:
# Multiplicación de tensores de más dimensión

# Definir los tensores
A = torch.randint(1, 5, (2, 2, 3))
B = torch.randint(1, 5, (3, 2, 2))

# Realizar la multiplicación sobre el índice compartido
C = torch.tensordot(A, B, dims=([2], [0]))

print("Forma del tensor resultante C:", C.shape)
print("Tensor resultante C:")
print(C)


Forma del tensor resultante C: torch.Size([2, 2, 2, 2])
Tensor resultante C:
tensor([[[[10, 13],
          [26, 18]],

         [[17, 17],
          [30, 23]]],


        [[[18, 17],
          [32, 22]],

         [[20, 21],
          [40, 28]]]])


In [13]:
# Suma elemento a elemento

# Definir las matrices
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)

# Sumar elemento a elemento
suma = torch.add(A, B)

print("La suma elemento a elemento de A y B es:")
print(suma)

# Multiplicación elemento a elemento
# Definir las matrices
A = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6],
                  [7, 8]], dtype=torch.float32)

# Multiplicar elemento a elemento
producto_hadamard = A * B

print("El producto elemento a elemento de A y B es:")
print(producto_hadamard)

La suma elemento a elemento de A y B es:
tensor([[ 6.,  8.],
        [10., 12.]])
El producto elemento a elemento de A y B es:
tensor([[ 5., 12.],
        [21., 32.]])


## Uso de GPU para realizar operaciones tensoriales

Las GPUs (Unidades de Procesamiento Gráfico) son dispositivos altamente paralelos diseñados originalmente para manejar cálculos gráficos intensivos. En el contexto del aprendizaje profundo y las operaciones tensoriales, las GPUs ofrecen ventajas significativas sobre las CPUs:

- Paralelización: Las GPUs contienen miles de núcleos que pueden ejecutar miles de hilos simultáneamente, lo que permite procesar grandes cantidades de datos en paralelo.
- Ancho de Banda de Memoria: Las GPUs tienen un ancho de banda de memoria mucho mayor que las CPUs, lo que facilita la transferencia rápida de datos.
- Optimización para Cálculos Matriciales: Las arquitecturas de GPU están optimizadas para operaciones matriciales y vectoriales, que son fundamentales en el aprendizaje profundo.

Los frameworks como TensorFlow y PyTorch están diseñados para aprovechar estas capacidades, permitiendo que las operaciones tensoriales se ejecuten en GPUs con mínima intervención del usuario.

### Ejemplo de uso de TensorFlow en GPU

In [14]:
import tensorflow as tf

# Verificar si hay una GPU disponible
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# Definir los tensores en el contexto de la GPU
with tf.device('/GPU:0'):
    # Crear tensores aleatorios grandes
    A = tf.random.uniform([1000, 1000], minval=0, maxval=1)
    B = tf.random.uniform([1000, 1000], minval=0, maxval=1)

    # Realizar una multiplicación de matrices
    C = tf.matmul(A, B)

    # Realizar una suma elemento a elemento
    D = tf.add(A, B)

    # Calcular el producto elemento a elemento
    E = tf.multiply(A, B)

# Ejecutar y obtener los resultados
print("Operaciones realizadas en GPU.")

GPU disponible: []
Operaciones realizadas en GPU.


### Ejemplo de uso de pyTorch en GPU

In [15]:
import torch

# Verificar si hay una GPU disponible
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Dispositivo utilizado:", device)

# Crear tensores aleatorios grandes y moverlos al dispositivo (GPU o CPU)
A = torch.rand(1000, 1000, device=device)
B = torch.rand(1000, 1000, device=device)

# Realizar una multiplicación de matrices
C = torch.matmul(A, B)

# Realizar una suma elemento a elemento
D = torch.add(A, B)

# Calcular el producto elemento a elemento
E = torch.mul(A, B)

print("Operaciones realizadas en", device)


Dispositivo utilizado: cuda
Operaciones realizadas en cuda


### Prueba de cpu vs gpu

In [19]:
import torch
import time

# Determinar si hay una GPU disponible
device_cpu = torch.device('cpu')
device_gpu = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print("GPU disponible:", torch.cuda.is_available())


# Definir una función para medir el tiempo de ejecución
def benchmark(device, size=10000):
    # Crear tensores aleatorios grandes en el dispositivo especificado
    A = torch.rand(size, size, device=device)
    B = torch.rand(size, size, device=device)

    # Sincronizar antes de empezar la medición de tiempo
    if device.type == 'cuda':
        torch.cuda.synchronize()

    start_time = time.time()

    # Realizar operaciones tensoriales complejas
    for _ in range(10):
        C = torch.matmul(A, B)
        D = torch.add(A, B)
        E = torch.mul(A, B)
        F = torch.sin(C)
        G = torch.exp(D)

    # Sincronizar nuevamente después de las operaciones
    if device.type == 'cuda':
        torch.cuda.synchronize()

    end_time = time.time()
    return end_time - start_time

# Tamaño de los tensores
tensor_size = 1024*8  # Ajusta este valor según la capacidad de tu hardware

# Medir tiempo en CPU
time_cpu = benchmark(device_cpu, size=tensor_size)
print(f"Tiempo en CPU: {time_cpu:.4f} segundos")

# Medir tiempo en GPU (si está disponible)
if device_gpu.type == 'cuda':
    time_gpu = benchmark(device_gpu, size=tensor_size)
    print(f"Tiempo en GPU: {time_gpu:.4f} segundos")
    print(f"La GPU fue {time_cpu / time_gpu:.2f} veces más rápida que la CPU.")
else:
    print("No hay GPU disponible para realizar la comparación.")

GPU disponible: True
Tiempo en CPU: 15.7036 segundos
Tiempo en GPU: 1.2756 segundos
La GPU fue 12.31 veces más rápida que la CPU.
